
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BRADER = 5;
  public static final int SPECHAR = 20;
  public static final int IDENT = 7;
  public static final int CADENA = 19;
  public static final int CONJUNTO = 18;
  public static final int CONCAT = 13;
  public static final int PERCEN = 9;
  public static final int LETR = 10;
  public static final int ASIGN = 8;
  public static final int COMA = 21;
  public static final int EOF = 0;
  public static final int VIRG = 4;
  public static final int DIGITO = 11;
  public static final int DIS = 14;
  public static final int error = 1;
  public static final int ASCII = 12;
  public static final int INTER = 17;
  public static final int KLE = 15;
  public static final int DOSPTO = 3;
  public static final int MAS = 16;
  public static final int PTCOMA = 2;
  public static final int BRAIZQ = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "DOSPTO",
  "VIRG",
  "BRADER",
  "BRAIZQ",
  "IDENT",
  "ASIGN",
  "PERCEN",
  "LETR",
  "DIGITO",
  "ASCII",
  "CONCAT",
  "DIS",
  "KLE",
  "MAS",
  "INTER",
  "CONJUNTO",
  "CADENA",
  "SPECHAR",
  "COMA"
  };
}

